[ ] // Types used by the Assay Factory GUI
[ ] 
[-] type REC_ASSAY is record
	[ ] STRING sSourceName
	[ ] STRING sDestName
	[ ] STRING sAssayType
	[ ] STRING sLotNumber
	[ ] STRING sSheet
[ ] 
[-] type DETAIL_CHANGES is record
	[ ] STRING sAnalyteName
	[ ] STRING sNormFactor
	[ ] STRING sPrbChk13Max
	[ ] STRING sPrbChk2Min
	[ ] STRING sDeltaCtE
	[ ] STRING sScalingFactor
[ ] 
[-] type REC_ASSAY_NONLSP is record
	[ ] STRING sSourceName
	[ ] STRING sDestName
	[ ] STRING sAssayType
	[ ] STRING sDisclaimer
[ ] 
