[ ] //
[ ] // Installer Checklist Constants
[ ] //
[ ] const CD_ROOT = "CD root"
[ ] const C_DRIVE = 'C'
[ ] const D_DRIVE = 'D'
[ ] const YES = "Yes"
[ ] const NO = "No"
[ ] const NOT_APPLICABLE = "NA"
[ ] const HIDDEN = 'H'
[ ] const ARCHIVE = 'A'
[ ] const READ_ONLY = 'R'
[ ] const BLANK = ' '
[ ] const DBNULLVALUE = "-9999.000000"
[ ] const INSTALL_PLACEHOLDER = "*Install folder*"
[ ] const INSTALL_PATTERN = "<Install folder>"
[ ] 
[ ] const INSTALL_FOLDER = "C:\Program Files\Cepheid\GeneXpert"
