[ ] 
[-] window JavaMainWin GeneXpertInfinity
	[ ] tag "GeneXpert® Infinity"
	[-] JavaJFCPushButton HtmlCenterFontColorBla
		[ ] tag "<html><center><font color='black'>YES<?font><?center><?html>"
	[-] JavaJFCPushButton HtmlCenterFontColorBla1
		[ ] tag "<html><center><font color='black'>DATABASE RESTORE<?font><?center><?html>"
	[-] JavaJFCPushButton HtmlCenterFontColorBla2
		[ ] tag "<html><center><font color='black'>PROCEED<?font><?center><?html>"
	[-] JavaJFCListBox LookIn
		[ ] tag "Look In:"
	[-] JavaJFCPushButton HtmlCenterFontColorBla3
		[ ] tag "<html><center><font color='black'>OPEN<?font><?center><?html>"
